languageCode = "en-au"
languageName = "English (Australia)"
displayName = ":flag-au:"
isoCode = "en-AU"
weight = 1
rtl = false

title = "smpltn"
# logo = "img/logo.jpg"
description = "Telling Stories to the Sea"
copyright = "&copy; 2022 Rob Gale"

dateFormat = "January 2, 2006"

[author]
  name = "Rob Gale"
  image = "img/author.jpg"
  headline = "Writing. Drawing. Process. Ideas."
  bio = "Rob Gale is an illustrator, art director, and writer. He writes about the creative process from the Bay Area."
  links = [
    # { website = "https://robgale.co"},
    { twitter = "https://twitter.com/robgalestudio" },
    { linkedin = "https://linkedin.com/in/robgalestudio" },
  ]
